title = "zmperf"

data_root = "/home/xxx/zmatrix"

val_size = "900B"
job_type = "embed"
job_time = 200
skip_time = 10

mb_per_get_thread = 1024
get_threads = 64

io_threads = 32

is_do_nothing = false

server_addr = ""

print_log = false